osx_image: xcode7.3
language: objective-c
env:
  global:
  - FASTLANE_SKIP_UPDATE_CHECK=true
  - FASTLANE_XCODE_LIST_TIMEOUT=30
install:
- bundle install
- bundle exec pod repo update
- bundle exec fastlane ios test
- bundle exec fastlane ios fabric
after_success:
- sleep 5
- bash <(curl -s https://codecov.io/bash) -J 'Reddit'
